plugins:
  - uses:
      - plugin: https://ubiquity-os-command-start-stop-development.fernand-veyrier.workers.dev
        skipBotEvents: false
        with:
          maxConcurrentTasks:
            collaborator: 999999
            contributor: 999999
  - uses:
      - plugin: https://ubiquity-os-plugin-demo-fix-collaborator-add.fernand-veyrier.workers.dev
  #      - plugin: https://ubiquity-os-plugin-demo-development.fernand-veyrier.workers.dev
  - uses:
      - plugin: https://ubiquity-os-command-wallet-development.fernand-veyrier.workers.dev
  - uses:
      - plugin: Meniole/command-ask@development
        with:
          model: anthropic/claude-3.5-sonnet
          openAiBaseUrl: https://openrouter.ai/api/v1
  - uses:
      - plugin: https://ubiquity-os-command-query-user-development.fernand-veyrier.workers.dev
  - uses:
      - plugin: "Meniole/text-conversation-rewards@demo"
        skipBotEvents: false
        with:
          incentives:
            collaboratorOnlyPaymentInvocation: false
            contentEvaluator: {}
            userExtractor: {}
            dataPurge: {}
            formattingEvaluator: {}
            permitGeneration: {}
            githubComment: {}
          evmPrivateEncrypted: ""
          erc20RewardToken: "0xC6ed4f520f6A4e4DC27273509239b7F8A68d2068"
          evmNetworkId: 100
  - uses:
      - plugin: Meniole/daemon-disqualifier@development
  - uses:
      - plugin: https://ubiquity-os-comment-vector-embeddings-development.fernand-veyrier.workers.dev
